//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryMax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryMax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above maximum charge {0}%.
        /// </summary>
        internal static string AboveMaximumCharge {
            get {
                return ResourceManager.GetString("AboveMaximumCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery not found.
        /// </summary>
        internal static string BatteryNotFound {
            get {
                return ResourceManager.GetString("BatteryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below minimum charge {0}%.
        /// </summary>
        internal static string BelowMinimumCharge {
            get {
                return ResourceManager.GetString("BelowMinimumCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% charging.
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hr to {1}%.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hr {1} min to {2}%.
        /// </summary>
        internal static string HourMin {
            get {
                return ResourceManager.GetString("HourMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min to {1}%.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not charging.
        /// </summary>
        internal static string NotCharging {
            get {
                return ResourceManager.GetString("NotCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% plugged in.
        /// </summary>
        internal static string PluggedIn {
            get {
                return ResourceManager.GetString("PluggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% remaining.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456789012345678901234567890123456789012345678901234567890123.
        /// </summary>
        internal static string TooltipMaxLength {
            get {
                return ResourceManager.GetString("TooltipMaxLength", resourceCulture);
            }
        }
    }
}
