//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryMax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryMax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery not found.
        /// </summary>
        internal static string BatteryNotFound {
            get {
                return ResourceManager.GetString("BatteryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% charging.
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% charging. Above maximum {1}%.
        /// </summary>
        internal static string ChargingAboveMaximum {
            get {
                return ResourceManager.GetString("ChargingAboveMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% charging. {1} hr to {2}%.
        /// </summary>
        internal static string ChargingHour {
            get {
                return ResourceManager.GetString("ChargingHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% charging. {1} hr {2} min to {3}%.
        /// </summary>
        internal static string ChargingHourMin {
            get {
                return ResourceManager.GetString("ChargingHourMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% charging. {1} min to {2}%.
        /// </summary>
        internal static string ChargingMin {
            get {
                return ResourceManager.GetString("ChargingMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% plugged in. Not charging.
        /// </summary>
        internal static string PluggedInNotCharging {
            get {
                return ResourceManager.GetString("PluggedInNotCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% remaining.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% remaining. Below minimum is {1}%.
        /// </summary>
        internal static string RemainingBelowMinimum {
            get {
                return ResourceManager.GetString("RemainingBelowMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% remaining. {1} hr to {2}%.
        /// </summary>
        internal static string RemainingHour {
            get {
                return ResourceManager.GetString("RemainingHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% remaining. {1} hr {2} min to {3}%.
        /// </summary>
        internal static string RemainingHourMin {
            get {
                return ResourceManager.GetString("RemainingHourMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% remaining. {1} min to {2}%.
        /// </summary>
        internal static string RemainingMin {
            get {
                return ResourceManager.GetString("RemainingMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456789012345678901234567890123456789012345678901234567890123.
        /// </summary>
        internal static string TooltipMaxLength {
            get {
                return ResourceManager.GetString("TooltipMaxLength", resourceCulture);
            }
        }
    }
}
